version: '3'
services:
  eureka-server:
    image: server
    container_name: eureka-server
    ports:
      - "8761:8761"

  gateway:
    image: gateway
    container_name: service-gateway
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_DISCOVERY_ENABLED=true
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server

  service-car:
    image: voiture
    container_name: service-car
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-car:3306/carservicedb
    depends_on:
      - eureka-server
      - mysql-car

  service-client:
    image: client
    container_name: service-client
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-client:3306/dbservice
    depends_on:
      - eureka-server
      - mysql-client

  mysql-car:  
    image: mysql:latest
    container_name: mysql-car
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=carservicedb

  mysql-client:
    image: mysql:latest
    container_name: mysql-client
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbservice